### ISSUE TITLE
Can't change to custom map on the server.

### ISSUE THREAD

**Issue by Sinkcat113** [Triang3l/WebQuake#50]
When trying to change to a custom map/level that's in my id1/maps folder it seems to work but when I join with the client the server crashes with this error.

```
IFNOT     4100(???)            branch 23
client.qc    : SelectSpawnPoint
client.qc    : PutClientInServer
<NO FUNCTION>
runaway loop error
Host.Error: Program error
Host.Error: Program error

C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Sys.js:16
        throw new Error(text);
        ^

Error: Host.Error: Program error

    at Sys.Error (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Sys.js:16:8)
    at Host.Error (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Host.js:12:6)
    at PR.RunError (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\PR.js:562:7)
    at PR.ExecuteProgram (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\PR.js:618:7)
    at Host.Spawn_f [as command] (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Host.js:656:5)
    at SV.ReadClientMessage (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\SV.js:2014:10)
    at SV.RunClients (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\SV.js:2042:10)
    at Host.ServerFrame (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Host.js:200:5)
    at Host._Frame (C:\Users\Sinkcat\Desktop\WebQuake\WebQuake\Server\WebQDS\Host.js:225:8)

Node.js v22.11.0
```

**Comment by Sinkcat113** [comment]
Okay apparently its for any BSP.
